### ISSUE TITLE
idk 

### ISSUE THREAD

**Issue by justlofe** [JNNGL/vanilla-shaders#2]
не стартует simple ao.
кубы 1.21
(мб содиум мешает? не проверял)

`[08:34:57] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:537) [client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 18 more
Caused by: net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/core/rendertype_entity_translucent_cull.json: 
	at net.minecraft.class_2973.handler$bic000$iris$changeShaderParseException(class_2973.java:516) ~[client-intermediary.jar:?]
	at net.minecraft.class_2973.method_12856(class_2973.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:497) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 18 more
Caused by: net.irisshaders.iris.gl.shader.ShaderCompileException: rendertype_entity_translucent_cull.vsh: rendertype_entity_translucent_cull.vsh: 0(43) : error C1102: incompatible type for parameter #1 ("pos.21")
0(43) : error C7623: implicit narrowing of type from "vec3" to "int"
0(43) : error C1104: too many parameters in function call

	at net.minecraft.class_281.handler$bjk000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:497) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 18 more`

**Comment by JNNGL** [comment]
оно для 1.20.4

**Comment by JNNGL** [comment]
убери ModelViewMat из вызова fog_distance
https://github.com/JNNGL/vanilla-shaders/blob/620c5d46eb2934482c814645a063e5f2d03a0108/simple_ao/assets/minecraft/shaders/core/rendertype_entity_translucent_cull.vsh#L43

и поменяй `transpose(mat4(IViewRotMat))` на `ModelViewMat`
https://github.com/JNNGL/vanilla-shaders/blob/620c5d46eb2934482c814645a063e5f2d03a0108/simple_ao/assets/minecraft/shaders/core/rendertype_entity_translucent_cull.fsh#L83

**Comment by justlofe** [comment]
мб тогда ветку для 1.21 сделать? я пр сделаю

**Comment by JNNGL** [comment]
лучше просто в readme добавить как обновлять до 1.20.5+

**Comment by justlofe** [comment]
https://i.imgur.com/dTDUy5S.mp4

**Comment by JNNGL** [comment]
/summon item_display ~ ~ ~ {item:{id:leather_horse_armor,Count:1,components:{custom_model_data:1}}}
